### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by Ann-Barnshaw** [lillian-busingye/loginpage#1]
https://github.com/lillian-busingye/loginpage/blob/8bf87cf2b817daa92b6e0f8657572ada3a5e0602/index.html#L7

Hi @lillian-busingye ,

Well done. 

I suggest that you use a title that describes the content of your code. WDYT?

**Comment by lillian-busingye** [comment]
@Ann-Barnshaw thanks for the reminder, I have updated it.
